#!/bin/bash -ex
ulimit -s 50000

source ./setenv

rm -rf build
mkdir -p build
cd build

cmake .. \
  -DCMAKE_BUILD_TYPE=$1 \
  -DCMAKE_INSTALL_PREFIX=install \
  -DGC_THRESHOLD=1 \
  -DBUILD_TESTS=On

make -j`nproc`
if [[ "$1" == "GcStats"* ]]; then
  make install
  exit 0
fi

make test
cd ../matching
mvn verify -U
cd ../build

export PATH="`pwd`/install/bin:`pwd`/bin:$PATH"
make install

lit -v ../test
