#!/bin/bash -ex
export PATH=$PATH:~/.cargo/bin
mkdir -p build
cd build
CC=clang-6.0 CXX=clang++-6.0 cmake .. -DCMAKE_BUILD_TYPE=Debug
make -j`nproc`
make run-unittests
cd ../runtime/datastructures
cargo test
cd ../../matching
stack test
stack install
cd ../build

export PATH=$PATH:`pwd`/install/bin
make install
llvm-kompile ../test/imp.kore IMP -o interpreter
./interpreter ../test/collatz.kore -1 /dev/stdout | grep -q "Lbl'-LT-'T'-GT-'{}(Lbl'-LT-'k'-GT-'{}(dotk{}())"
llvm-kompile ../test/test2.kore TEST -o interpreter
./interpreter ../test/test2.kore -1 /dev/stdout | grep -q "Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortDone{}, SortKItem{}}(Lbldone'Unds'TEST'Unds'{}()),dotk{}()))"
llvm-kompile ../test/test3.kore TEST -o interpreter
./interpreter ../test/test3.kore -1 /dev/stdout | grep -q "Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortDone{}, SortKItem{}}(Lbldone'Unds'TEST'Unds'{}()),dotk{}()))"
llvm-kompile ../test/test4.kore TEST -o interpreter
./interpreter ../test/test4.kore -1 /dev/stdout | diff - ../test/test4.out
llvm-kompile ../test/test5.kore TEST -o interpreter
./interpreter ../test/test5.kore -1 /dev/stdout | diff - ../test/test5.out
llvm-kompile ../test/test6.kore TEST -o interpreter
./interpreter ../test/test6.kore -1 /dev/stdout | diff - ../test/test6.out
llvm-kompile ../test/test7.kore TEST -o interpreter
./interpreter ../test/test7.in.kore -1 /dev/null
rm -f configparser configparser.ll interpreterQ
