#!/bin/bash -ex
export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH

if [[ "$OSTYPE" == "darwin"* ]]; then
    BREW_PREFIX=$(brew --prefix || true)
    if [ -z "${BREW_PREFIX}" ]; then
      BREW_PREFIX="/usr/local"
    fi

    export PATH="${BREW_PREFIX}/opt/flex/bin:${BREW_PREFIX}/opt/llvm@13/bin:$PATH"
    export LDFLAGS="-L${BREW_PREFIX}/opt/llvm@13/lib -L${BREW_PREFIX}/opt/flex/lib"
    export CPPFLAGS="-I${BREW_PREFIX}/opt/llvm@13/include -I${BREW_PREFIX}/opt/flex/include"
    export FLEX_EXECUTABLE="${BREW_PREFIX}/opt/flex/bin/flex"
fi

rm -rf build
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=$1 -DCMAKE_INSTALL_PREFIX=install -DGC_THRESHOLD=1
make -j`nproc`
if [[ "$1" == "GcStats"* ]]; then
  make install
  exit 0
fi
make run-unittests
cd ../matching
mvn verify -U
cd ../build

export PATH="`pwd`/install/bin:`pwd`/bin:$PATH"
make install

TEST_DIR=../test

lit $TEST_DIR

cd $TEST_DIR/defn
diff io_output1.txt ../ioTest1.output
diff `ls | grep io_log` ../ioTest3.output
rm `ls | grep io_log`
ls test-foo*
rm `ls | grep test-foo`
cd ../../build

make -C ../test/unparse -j`nproc`
