#!/bin/sh -e
curl -L https://static.rust-lang.org/dist/rustc-1.33.0-src.tar.gz -o rustc-src.tar.gz
tar xvf rustc-src.tar.gz
cd rustc-1.33.0-src
./configure --llvm-root=/usr/lib/llvm-6.0 --enable-llvm-link-shared
./x.py install
cd ..
rm -rf rustc-1.33.0-src rustc-src.tar.gz

apt-get install -y cargo
git clone https://github.com/rust-lang/cargo -b rust-1.33.0 --depth 1
cd cargo
cargo build --release
cargo install --path . --root /usr/local
apt-get remove -y cargo rustc
