#!/bin/bash -e
curl -L https://static.rust-lang.org/dist/rustc-1.33.0-src.tar.gz -o rustc-src.tar.gz
shasum -a 512 -c "$(dirname "$0")/rust-checksum"

curl https://sh.rustup.rs -sSf | sh -s -- -y
source ~/.cargo/env

tar xvf rustc-src.tar.gz
cd rustc-1.33.0-src
./configure --llvm-root=`llvm-config-6.0 --prefix` --enable-llvm-link-shared
./x.py build
if [[ "$OSTYPE" == "darwin"* ]]; then
  triple=x86_64-apple-darwin
else
  triple=x86_64-unknown-linux-gnu
fi
rustup toolchain link rust-1.33.0-llvm-6.0 build/$triple/stage2
cd ..
rm -rf rustc-src.tar.gz
