#!/bin/bash -e
curl -L https://static.rust-lang.org/dist/rustc-1.34.0-src.tar.gz -o rustc-src.tar.gz
shasum -a 512 -c "$(dirname "$0")/rust-checksum"

curl https://sh.rustup.rs -sSf | sh -s -- -y
source ~/.cargo/env

if [[ "$OSTYPE" == "darwin"* ]]; then
    export PATH="/usr/local/opt/llvm@6/bin:$PATH"
    export RUSTFLAGS="-C link-arg=-L/usr/local/opt/libffi/lib -C link-arg=-lffi"
    export CONFIGFLAGS=""
else
    export CONFIGFLAGS="--enable-llvm-link-shared"
fi

tar xf rustc-src.tar.gz > /dev/null
cd rustc-1.34.0-src
./configure --llvm-root=`llvm-config-6.0 --prefix 2>/dev/null || llvm-config --prefix` $CONFIGFLAGS
./x.py build
if [[ "$OSTYPE" == "darwin"* ]]; then
  triple=x86_64-apple-darwin
else
  triple=x86_64-unknown-linux-gnu
fi
rustup toolchain link rust-1.34.0-llvm-6.0 build/$triple/stage2
cd ..
rm -rf rustc-src.tar.gz
