#include <boost/test/unit_test.hpp>

#include "../../runtime/collections/rangemap.h"

BOOST_AUTO_TEST_SUITE(TreeMapTest)

BOOST_AUTO_TEST_CASE(rangemap_test_empty) {
  auto map = RangeMap<int, int>();
  auto result = map.size();
  BOOST_CHECK_EQUAL(result, 0);
  auto result2 = map.containsKey(0);
  BOOST_CHECK_EQUAL(result2, false);
}

BOOST_AUTO_TEST_CASE(rangemap_test_contains_key) {
  auto m1 = (RangeMap<int, int>()).inserted(std::make_pair(0,5), 1);
  auto m2 = m1.inserted(std::make_pair(2,4), 2);
  auto map = m2.deleted(std::make_pair(3,4));
  auto result = map.size();
  BOOST_CHECK_EQUAL(result, 3);
  auto result2 = map.containsKey(0);
  BOOST_CHECK_EQUAL(result2, true);
  result2 = map.containsKey(2);
  BOOST_CHECK_EQUAL(result2, true);
  result2 = map.containsKey(3);
  BOOST_CHECK_EQUAL(result2, false);
  result2 = map.containsKey(4);
  BOOST_CHECK_EQUAL(result2, true);
  result2 = map.containsKey(5);
  BOOST_CHECK_EQUAL(result2, false);
  result2 = map.containsKey(6);
  BOOST_CHECK_EQUAL(result2, false);
}

BOOST_AUTO_TEST_CASE(rangemap_test_vlookup) {
  auto m1 = (RangeMap<int, int>()).inserted(std::make_pair(0,5), 1);
  auto m2 = m1.inserted(std::make_pair(2,4), 2);
  auto map = m2.deleted(std::make_pair(3,4));
  auto result = map.size();
  BOOST_CHECK_EQUAL(result, 3);
  auto result2 = map.getValue(0);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value(), 1);
  result2 = map.getValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value(), 2);
  result2 = map.getValue(3);
  BOOST_CHECK_EQUAL(result2.has_value(), false);
  result2 = map.getValue(4);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value(), 1);
  result2 = map.getValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), false);
  result2 = map.getValue(6);
  BOOST_CHECK_EQUAL(result2.has_value(), false);
}

BOOST_AUTO_TEST_CASE(rangemap_test_kvlookup) {
  auto m1 = (RangeMap<int, int>()).inserted(std::make_pair(0,5), 1);
  auto m2 = m1.inserted(std::make_pair(2,4), 2);
  auto map = m2.deleted(std::make_pair(3,4));
  auto result = map.size();
  BOOST_CHECK_EQUAL(result, 3);
  auto result2 = map.getKeyValue(0);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 2);
  result2 = map.getKeyValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 3);
  result2 = map.getKeyValue(3);
  BOOST_CHECK_EQUAL(result2.has_value(), false);
  result2 = map.getKeyValue(4);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 4);
  BOOST_CHECK_EQUAL(result2.value().first.second, 5);
  result2 = map.getKeyValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), false);
  result2 = map.getKeyValue(6);
  BOOST_CHECK_EQUAL(result2.has_value(), false);
}

BOOST_AUTO_TEST_CASE(rangemap_test_ins_1) {
  auto map = (RangeMap<int, int>()).inserted(std::make_pair(0,5), 1);
  auto result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  auto map2 = map.inserted(std::make_pair(2,4), 2);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map2.size();
  BOOST_CHECK_EQUAL(result, 3);
  auto result2 = map2.getKeyValue(0);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 2);
  result2 = map2.getKeyValue(1);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 2);
  result2 = map2.getKeyValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 4);
  result2 = map2.getKeyValue(3);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 4);
  result2 = map2.getKeyValue(4);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 4);
  BOOST_CHECK_EQUAL(result2.value().first.second, 5);
  result2 = map2.getKeyValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), false);
}

BOOST_AUTO_TEST_CASE(rangemap_test_ins_2) {
  auto map = (RangeMap<int, int>()).inserted(std::make_pair(2,5), 1);
  auto result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  auto map2 = map.inserted(std::make_pair(4,7), 2);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map2.size();
  BOOST_CHECK_EQUAL(result, 2);
  auto result2 = map2.getKeyValue(4);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 4);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  result2 = map2.getKeyValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 4);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  auto map3 = map.inserted(std::make_pair(5,7), 2);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map3.size();
  BOOST_CHECK_EQUAL(result, 2);
  result2 = map3.getKeyValue(4);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 5);
  result2 = map3.getKeyValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 5);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  auto map4 = map.inserted(std::make_pair(4,7), 1);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map4.size();
  BOOST_CHECK_EQUAL(result, 1);
  result2 = map4.getKeyValue(4);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  result2 = map4.getKeyValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  auto map5 = map.inserted(std::make_pair(5,7), 1);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map5.size();
  BOOST_CHECK_EQUAL(result, 1);
  result2 = map5.getKeyValue(4);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  result2 = map5.getKeyValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  auto map6 = map.inserted(std::make_pair(0,3), 2);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map6.size();
  BOOST_CHECK_EQUAL(result, 2);
  result2 = map6.getKeyValue(1);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 3);
  result2 = map6.getKeyValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 3);
  auto map7 = map.inserted(std::make_pair(0,2), 2);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map7.size();
  BOOST_CHECK_EQUAL(result, 2);
  result2 = map7.getKeyValue(1);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 2);
  result2 = map7.getKeyValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 2);
  BOOST_CHECK_EQUAL(result2.value().first.second, 5);
  auto map8 = map.inserted(std::make_pair(0,3), 1);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map8.size();
  BOOST_CHECK_EQUAL(result, 1);
  result2 = map8.getKeyValue(1);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 5);
  result2 = map8.getKeyValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 5);
  auto map9 = map.inserted(std::make_pair(0,2), 1);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map9.size();
  BOOST_CHECK_EQUAL(result, 1);
  result2 = map9.getKeyValue(1);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 5);
  result2 = map9.getKeyValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 0);
  BOOST_CHECK_EQUAL(result2.value().first.second, 5);
  auto map10 = map.inserted(std::make_pair(1,7), 2);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map10.size();
  BOOST_CHECK_EQUAL(result, 1);
  result2 = map10.getKeyValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 1);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  result2 = map10.getKeyValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 2);
  BOOST_CHECK_EQUAL(result2.value().first.first, 1);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  auto map11 = map.inserted(std::make_pair(1,7), 1);
  result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  result = map11.size();
  BOOST_CHECK_EQUAL(result, 1);
  result2 = map11.getKeyValue(2);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 1);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
  result2 = map11.getKeyValue(5);
  BOOST_CHECK_EQUAL(result2.has_value(), true);
  BOOST_CHECK_EQUAL(result2.value().second, 1);
  BOOST_CHECK_EQUAL(result2.value().first.first, 1);
  BOOST_CHECK_EQUAL(result2.value().first.second, 7);
}

BOOST_AUTO_TEST_CASE(rangemap_test_ins_3) {
  auto map = (RangeMap<int, int>()).inserted(std::make_pair(0,5), 1);
  auto result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  auto map2 = map.inserted(std::make_pair(10,15), 1);
  result = map2.size();
  BOOST_CHECK_EQUAL(result, 2);
  map2.print();
  auto map3 = map2.inserted(std::make_pair(5,10), 1);
  result = map3.size();
  BOOST_CHECK_EQUAL(result, 1);
  map3.print();
  auto map4 = map2.inserted(std::make_pair(4,10), 1);
  result = map4.size();
  BOOST_CHECK_EQUAL(result, 1);
  map4.print();
  auto map5 = map2.inserted(std::make_pair(5,11), 1);
  result = map5.size();
  BOOST_CHECK_EQUAL(result, 1);
  map5.print();
  auto map6 = map2.inserted(std::make_pair(4,11), 1);
  result = map6.size();
  BOOST_CHECK_EQUAL(result, 1);
  map6.print();
  auto map7 = map2.inserted(std::make_pair(5,10), 2);
  result = map7.size();
  BOOST_CHECK_EQUAL(result, 3);
  map7.print();
  auto map8 = map2.inserted(std::make_pair(4,10), 2);
  result = map8.size();
  BOOST_CHECK_EQUAL(result, 3);
  map8.print();
  auto map9 = map2.inserted(std::make_pair(5,11), 2);
  result = map9.size();
  BOOST_CHECK_EQUAL(result, 3);
  map9.print();
  auto map10 = map2.inserted(std::make_pair(4,11), 2);
  result = map10.size();
  BOOST_CHECK_EQUAL(result, 3);
  map10.print();
}

BOOST_AUTO_TEST_CASE(rangemap_test_del) {
  auto map = (RangeMap<int, int>()).inserted(std::make_pair(0,10), 1);
  auto result = map.size();
  BOOST_CHECK_EQUAL(result, 1);
  auto map2 = map.inserted(std::make_pair(5,10), 2);
  result = map2.size();
  BOOST_CHECK_EQUAL(result, 2);
  map2.print();
  auto map3 = map2.deleted(std::make_pair(4,6));
  result = map3.size();
  BOOST_CHECK_EQUAL(result, 2);
  map3.print();
  auto map7 = map3.deleted(std::make_pair(3,10));
  result = map7.size();
  BOOST_CHECK_EQUAL(result, 1);
  map7.print();
  auto map4 = map3.deleted(std::make_pair(8,9));
  result = map4.size();
  BOOST_CHECK_EQUAL(result, 3);
  map4.print();
  auto map5 = map4.deleted(std::make_pair(3,10));
  result = map5.size();
  BOOST_CHECK_EQUAL(result, 1);
  map5.print();
  auto map6 = map5.deleted(std::make_pair(5,7));
  result = map6.size();
  BOOST_CHECK_EQUAL(result, 1);
  map6.print();
}


BOOST_AUTO_TEST_SUITE_END()
