[tool.poetry]
name = "kllvm"
version = "0.1.0"
description = ""
authors = ["Bruce Collie <brucecollie82@gmail.com>"]
readme = "README.md"
include = ["kllvm/*"]

[tool.poetry.dependencies]
python = ">=3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
