#ifndef RUNTIME_MACROS_H
#define RUNTIME_MACROS_H

#define NOT_YOUNG_OBJECT_BIT @NOT_YOUNG_OBJECT_BIT@
#define YOUNG_AGE_BIT @YOUNG_AGE_BIT@
#define FWD_PTR_BIT @FWD_PTR_BIT@
#define VARIABLE_BIT @VARIABLE_BIT@
#define LAYOUT_OFFSET @LAYOUT_OFFSET@
#define HDR_MASK @HDR_MASK@

#define MAP_LAYOUT @MAP_LAYOUT@
#define LIST_LAYOUT @LIST_LAYOUT@
#define SET_LAYOUT @SET_LAYOUT@
#define INT_LAYOUT @INT_LAYOUT@
#define FLOAT_LAYOUT @FLOAT_LAYOUT@
#define STRINGBUFFER_LAYOUT @STRINGBUFFER_LAYOUT@
#define BOOL_LAYOUT @BOOL_LAYOUT@
#define SYMBOL_LAYOUT @SYMBOL_LAYOUT@
#define VARIABLE_LAYOUT @VARIABLE_LAYOUT@

#define STRINGIFY(x) #x
#define TOSTRING(X) STRINGIFY(X)
#define INSTALL_PREFIX TOSTRING(@INSTALL_DIR_ABS_PATH@)

#endif
