find_program(CMAKE_C_COMPILER clang-8)
find_program(CMAKE_C_COMPILER clang-7)
find_program(CMAKE_C_COMPILER clang)
find_program(CMAKE_CXX_COMPILER clang++-8)
find_program(CMAKE_CXX_COMPILER clang++-7)
find_program(CMAKE_CXX_COMPILER clang++)
find_program(CMAKE_C_COMPILER_AR llvm-ar-8)
find_program(CMAKE_C_COMPILER_AR llvm-ar-7)
find_program(CMAKE_C_COMPILER_AR llvm-ar)
find_program(CMAKE_C_COMPILER_RANLIB llvm-ranlib-8)
find_program(CMAKE_C_COMPILER_RANLIB llvm-ranlib-7)
find_program(CMAKE_C_COMPILER_RANLIB llvm-ranlib)

