if (APPLE)
  if (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm64")
    SET(LLVM_BACKEND_DATALAYOUT "e-m:o-i64:64-i128:128-n32:64-S128")
  elseif (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
    SET(LLVM_BACKEND_DATALAYOUT "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128")
  else()
    message(SEND_ERROR "Unsupported host processor for macOS target: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
  endif()
elseif (UNIX)
  if (CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
    SET(LLVM_BACKEND_DATALAYOUT "e-m:e-i64:64-f80:128-n8:16:32:64-S128")
  else()
    message(SEND_ERROR "Unsupported host processor for generic Unix target: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
  endif()
else()
  message(SEND_ERROR "Unsupported target platform; cannot determine target triple. Compilation may not succeed")
endif()

message(STATUS "Using LLVM datalayout: ${LLVM_BACKEND_DATALAYOUT}")
message(STATUS "Using LLVM triple    : ${BACKEND_TARGET_TRIPLE}")
