#!/bin/bash
# aggregates data from --profile-matching and sums together identical ordinals, yielding table with ordinals and seconds
cat "$1" | awk '{sum[$1] += $2} END { for (i in sum) print i, sum[i]}' | sort -n -k2 | awk '{ print $1, $2 / 1000000000}'
